package frc.team449.subsystems.shooter

import edu.wpi.first.units.measure.Angle
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard
import edu.wpi.first.wpilibj2.command.SubsystemBase
import frc.team449.Constants
import org.littletonrobotics.junction.Logger
import org.littletonrobotics.junction.inputs.LoggableInputs

class ShooterSubsystem(
    private val io: ShooterIO
) : SubsystemBase() {
    //ignore the error in the ide, it's autogenerated
    private val inputs: ShooterIOInputsAutoLogged = ShooterIOInputesAutoLogged()

    override fun periodic() {
        io.updateInputs(inputs)
        Logger.processInputs("Shooter", inputs as LoggableInputs)
    }

    override fun simulationPeriodic() {
        io.simPeriodic()
    }

    fun shoot() {
        io.run(Constants.ShooterConstants.SHOOTER_VOLTAGE)
    }

    fun stop() {
        io.stop()
    }

    fun setHood(angle: Angle) {
        io.setHood(angle)
    }

    fun holdHood() {
        io.holdHood()
    }
}
