package frc.team449.subsystems.shooter

import edu.wpi.first.units.Units.Amps
import edu.wpi.first.units.Units.RadiansPerSecond
import edu.wpi.first.units.measure.Angle
import edu.wpi.first.units.measure.AngularVelocity
import edu.wpi.first.wpilibj2.command.Command
import edu.wpi.first.wpilibj2.command.Commands
import edu.wpi.first.wpilibj2.command.SubsystemBase
import edu.wpi.first.wpilibj2.command.WaitUntilCommand
import frc.team449.Constants.ShooterConstants.CURRENT_HOMING_STATOR_THRESH
import frc.team449.Constants.ShooterConstants.CURRENT_HOMING_VOLTAGE
import org.littletonrobotics.junction.Logger

class ShooterSubsystem(
    private val io: ShooterIO
) : SubsystemBase() {
    // ignore the error in the ide, it's autogenerated
    private val inputs: ShooterIOInputsAutoLogged = ShooterIOInputsAutoLogged()

    override fun periodic() {
        io.updateInputs(inputs)
        Logger.processInputs("Shooter", inputs)
    }

    override fun simulationPeriodic() {
        io.simPeriodic()
    }

    fun shoot(velocity: AngularVelocity): Command {
        return runOnce {
            println("shooting flywheel!")
            io.runFlywheelAtVelocity(velocity)
        }
    }

    fun stop(): Command {
        return runOnce {
            println("stopping flywheel")
            io.runFlywheelAtVelocity(RadiansPerSecond.of(0.0))
        }
    }

    fun setHood(angle: Angle): Command {
        return runOnce {
            io.setHoodPosition(angle)
        }
    }

    fun holdHood(): Command {
        return runOnce {
            io.setHoodPosition(io.getHoodPosition())
        }
    }

    fun atTolerance(): Boolean {
        return io.atTolerance()
    }

    fun currentHoming(): Command {
        return Commands.sequence(
            runOnce {
                io.setHoodVoltage(CURRENT_HOMING_VOLTAGE)
            },
            WaitUntilCommand { io.getHoodStatorCurrent().`in`(Amps) > CURRENT_HOMING_STATOR_THRESH },
            runOnce {
                io.stopHoodVoltage()
                io.resetHoodPosition()
            }
        )
    }
}
