package frc.team449.subsystems.shooter

import edu.wpi.first.math.filter.Debouncer
import edu.wpi.first.units.Units.Amps
import edu.wpi.first.units.measure.Angle
import edu.wpi.first.units.measure.AngularVelocity
import edu.wpi.first.wpilibj2.command.Command
import edu.wpi.first.wpilibj2.command.Commands
import edu.wpi.first.wpilibj2.command.SubsystemBase
import edu.wpi.first.wpilibj2.command.WaitUntilCommand
import frc.team449.Constants.ShooterConstants.CURRENT_HOMING_STATOR_THRESH
import frc.team449.Constants.ShooterConstants.CURRENT_HOMING_VOLTAGE
import frc.team449.Constants.ShooterConstants.HOMING_DEBOUNCE_TIME
import frc.team449.Constants.ShooterConstants.HOMING_DEBOUNCE_TYPE
import org.littletonrobotics.junction.Logger

class ShooterSubsystem(
    private val io: ShooterIO
) : SubsystemBase() {
    // ignore the error in the ide, it's autogenerated
    private val inputs: ShooterIOInputsAutoLogged = ShooterIOInputsAutoLogged()
    private val currentHomingDebouncer: Debouncer = Debouncer(HOMING_DEBOUNCE_TIME, HOMING_DEBOUNCE_TYPE)

    override fun periodic() {
        io.updateInputs(inputs)
        Logger.processInputs("Shooter", inputs)
    }

    override fun simulationPeriodic() {
        io.simPeriodic()
    }

    fun shoot(velocity: AngularVelocity): Command {
        return runOnce {
            println("shooting flywheel!")
            io.setFlywheelVelocity(velocity)
        }
    }

    fun stop(): Command {
        return runOnce {
            println("stopping flywheel")
            io.setFlywheelVoltage(0.0)
        }
    }

    fun setHood(angle: Angle): Command {
        return runOnce {
            io.setHoodPosition(angle)
        }
    }

    fun holdHood(): Command {
        return runOnce {
            io.setHoodPosition(io.getHoodPosition())
        }
    }

    fun atTolerance(): Boolean {
        return io.inTolerance()
    }

    fun currentHoming(): Command {
        return Commands.sequence(
            runOnce {
                io.setHoodVoltage(CURRENT_HOMING_VOLTAGE)
            },
            WaitUntilCommand { currentHomingDebouncer.calculate(io.getHoodStatorCurrent().`in`(Amps) > CURRENT_HOMING_STATOR_THRESH) },
            runOnce {
                io.stopHoodVoltage()
                io.resetHoodPosition()
            }
        )
    }
}
